#!/usr/bin/env ruby

require 'rubygems'
require 'open-uri'
require 'json'
require 'fileutils'

#	eventually this'll be in a yaml config file or something
#	Probably add :include or :exclude keys as well
GITHUB = {
	:repo  => "/Users/jakewendt/github_repo",	#	don't use the ~
	:login => 'jakewendt',	#	distinguish yourself
	:users => ['jakewendt','breakpointer','gunark','grimen','thoughtbot','chinasaur','gnufied','makandra','peter','aaronchi','wayneeseguin']
}



pwd = Dir.pwd
if File.exists?(GITHUB[:repo])
	if File.directory?(GITHUB[:repo])
		Dir.chdir(GITHUB[:repo])
	else
		puts
		puts	"#{GITHUB[:repo]} is not a directory?"
		puts
		exit
	end
else
	puts "#{GITHUB[:repo]} does not exist.  Creating..."
	FileUtils.mkdir(GITHUB[:repo]) 
end

GITHUB[:users].each do |user|
	puts user

	if File.exists?("#{GITHUB[:repo]}/#{user}")
		if File.directory?("#{GITHUB[:repo]}/#{user}")
			Dir.chdir("#{GITHUB[:repo]}/#{user}")
		else
			puts
			puts	"#{GITHUB[:repo]}/#{user} is not a directory?  Skipping user"
			puts
			next
		end
	else
		puts "#{GITHUB[:repo]}/#{user} does not exist.  Creating..."
		FileUtils.mkdir("#{GITHUB[:repo]}/#{user}") 
	end

	json = `curl http://github.com/api/v1/json/#{user}`
	
	response = JSON.parse(json)
	response['user']['repositories'].each do |repo|
		url = ( response['user']['login'] == (GITHUB[:login]||'') ) ? 
			"git@github.com:" : "git://github.com/"
		url << "#{repo['owner']}/#{repo['name']}.git"
		puts url
	
		if File.exists?(repo['name'])
			puts "#{repo['name']} exists.  Updating."
			if File.directory?(repo['name'])
				Dir.chdir("#{GITHUB[:repo]}/#{user}/#{repo['name']}")
				puts `git pull`
				Dir.chdir("#{GITHUB[:repo]}/#{user}")
			else
				"#{repo['name']} is not a directory.  Skipping."
			end
		else
			puts "#{repo['name']} does not exist.  Cloning."
			puts `git clone #{url}`
		end
	end
	Dir.chdir("#{GITHUB[:repo]}")
end
Dir.chdir(pwd)
